"""Schemas for Phase 3E Agentic Emergency Orchestration.

Defines structured data contracts for agent assessments, advisory action sequences,
data-source traceability, and operational briefings.
Preserves existing authoritative deterministic severity, response plans, and network policies.
"""
from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any
from pydantic import BaseModel, Field


class AgentProviderType(str, Enum):
    """Execution backend for agent assessment."""
    DETERMINISTIC = "DETERMINISTIC"
    LLM = "LLM"


class ActionStepStatus(str, Enum):
    """Operational status of a recommended sequence step."""
    COMPLETED = "COMPLETED"
    REQUIRED = "REQUIRED"
    ADVISORY = "ADVISORY"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"


class ActionStep(BaseModel):
    """One discrete step in the recommended emergency coordination sequence."""
    step_number: int
    title: str
    description: str
    status: ActionStepStatus = ActionStepStatus.ADVISORY
    advisory_only: bool = True


class SeverityAssessment(BaseModel):
    """Explainable severity assessment preserving original deterministic severity."""
    severity: str
    explanation: str
    is_deterministic: bool = True
    incident_type: str


class LocationAssessment(BaseModel):
    """Geospatial context and nearby emergency infrastructure summary."""
    location_name: str | None = None
    latitude: float | None = None
    longitude: float | None = None
    nearby_police_count: int = 0
    nearby_hospital_count: int = 0
    closest_police_facility: str | None = None
    closest_police_distance_km: float | None = None
    closest_hospital_facility: str | None = None
    closest_hospital_distance_km: float | None = None
    gps_fix_available: bool = False
    summary: str


class EvidenceAssessment(BaseModel):
    """Integrity and availability assessment of forensic snapshots and clips."""
    snapshot_available: bool = False
    snapshot_path: str | None = None
    video_available: bool = False
    video_path: str | None = None
    summary: str


class ResponseAssessment(BaseModel):
    """Explanation of deterministic response planner actions."""
    status: str
    police_recommended: bool = False
    medical_recommended: bool = False
    medical_conditional: bool = True
    actions_summary: str
    human_approval_required: bool = True


class NetworkAssessment(BaseModel):
    """Explanation of application-level transmission prioritization policy."""
    policy: str
    priority: str
    actual_network_control: bool = False
    control_plane_connected: bool = False
    summary: str


class DataSourceTraceability(BaseModel):
    """Traceability checklist proving claims are derived from verified system sources."""
    incident_report: bool = True
    response_planner: bool = True
    location_intelligence: bool = True
    evidence_metadata: bool = True
    network_policy: bool = True


class AgentAssessment(BaseModel):
    """Complete structured assessment generated by the agentic orchestration layer.

    Every field is explainable, traceable, and strictly decision-support only.
    Autonomous emergency dispatch is strictly prohibited.
    """
    incident_id: str
    situation_summary: str
    severity_assessment: SeverityAssessment
    location_assessment: LocationAssessment
    evidence_assessment: EvidenceAssessment
    response_assessment: ResponseAssessment
    network_assessment: NetworkAssessment
    recommended_sequence: list[ActionStep] = Field(default_factory=list)
    missing_information: list[str] = Field(default_factory=list)
    data_sources: DataSourceTraceability = Field(default_factory=DataSourceTraceability)
    confidence: float = Field(ge=0.0, le=1.0)
    human_approval_required: bool = True
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    source: str = "DETERMINISTIC_SUPERVISOR_AGENT"
    disclaimer: str = (
        "Agentic Intelligence provides situational briefing and decision support only. "
        "Deterministic safety logic is authoritative. Human verification and approval is strictly mandatory."
    )
