"""Capture-layer tests: source classification, file decode, EOF termination.

Uses the synthetic fixture (generated by scripts/make_test_video.py). These
tests do NOT run YOLO — they validate the frame plumbing only.
"""
from pathlib import Path

import numpy as np
import pytest

from suraksha.capture.stream import FrameEvent, StreamCapture
from suraksha.config import PROJECT_ROOT, CaptureConfig

FIXTURE = PROJECT_ROOT / "datasets" / "videos" / "test" / "synthetic_cctv.mp4"


@pytest.fixture(scope="module")
def fixture_path() -> Path:
    if not FIXTURE.exists():
        import subprocess
        import sys

        subprocess.run(
            [sys.executable, str(PROJECT_ROOT / "scripts" / "make_test_video.py")],
            check=True, cwd=PROJECT_ROOT,
        )
    assert FIXTURE.exists()
    return FIXTURE


def test_source_classification():
    assert StreamCapture._classify("rtsp://cam:554/live") == "stream"
    assert StreamCapture._classify("http://x/y.m3u8") == "stream"
    assert StreamCapture._classify("0") == "webcam"
    assert StreamCapture._classify("datasets/videos/test/x.mp4") == "file"


def test_file_decode_and_eof(fixture_path):
    cfg = CaptureConfig(rtsp_url=str(fixture_path), pace="fast", max_frames=0)
    with StreamCapture(cfg) as cap:
        assert cap.source_kind == "file"
        events = list(cap.frames())  # must TERMINATE at EOF
    assert len(events) >= 30
    assert all(isinstance(e, FrameEvent) for e in events)
    assert events[0].frame.ndim == 3
    assert events[0].source_fps > 0
    idxs = [e.frame_idx for e in events]
    assert idxs == sorted(set(idxs))  # strictly increasing, no dupes


def test_max_frames_limit(fixture_path):
    cfg = CaptureConfig(rtsp_url=str(fixture_path), pace="fast", max_frames=10)
    with StreamCapture(cfg) as cap:
        events = list(cap.frames())
    assert len(events) == 10


def test_missing_file_raises():
    cfg = CaptureConfig(rtsp_url="does/not/exist.mp4", pace="fast")
    cap = StreamCapture(cfg)
    with pytest.raises(ConnectionError):
        next(cap.frames())
    cap.release()


def test_stream_reconnect_retry_limit():
    """Verify stream reconnect honors max_reconnect_attempts and stops retrying."""
    cfg = CaptureConfig(
        rtsp_url="rtsp://invalid-stream-host:554/live",
        max_reconnect_attempts=3,
        reconnect_delay_s=0.01,
    )
    cap = StreamCapture(cfg)
    assert cap.source_kind == "stream"
    ok = cap._connect()
    assert not ok
    assert cap._attempts == 3
    cap.release()


def test_stream_reconnect_recovery():
    """Verify stream reconnect recovers transparently when connection succeeds after dropout."""
    cfg = CaptureConfig(
        rtsp_url="rtsp://recovering-stream-host:554/live",
        max_reconnect_attempts=5,
        reconnect_delay_s=0.01,
    )
    cap = StreamCapture(cfg)

    # Simulate: attempt 0 fails, attempt 1 fails, attempt 2 succeeds
    call_count = 0
    def mock_open():
        nonlocal call_count
        call_count += 1
        return call_count >= 3

    cap._open = mock_open
    ok = cap._connect()
    assert ok is True
    assert cap._attempts == 0  # resets on success
    assert call_count == 3
    cap.release()

